chore: Dropdown options should be enabled  for all users
bf2fc6cc711aee1a0c2a/kas-ui pull request #1264
Opened 2022-07-28 06:30 UTC by suyash-naithani

Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>

This issue fixes [9116](https://issues.redhat.com/browse/MGDSTRM-9116)

2022-08-03 09:00 UTC, ajaypratap003 commented on src/app/modules/OpenshiftStreams/components/StreamsTable/StreamsTable.tsx
> +        disabled: false,
we don't need to add disabled property. You should remove additionalProps and tooltipProps where we need to show kebab options for all users.

2022-08-03 09:01 UTC, ajaypratap003 requested changes
Follow inline comment.

2022-08-03 09:06 UTC, ajaypratap003 commented
@suyash-naithani  Please consider below minor changes related to this PR.
1. Make sure every row should show mouse hover pointer for all users. Fir now it's showing for org-admin and owner but not for non-owner.
2. Ever row should show vertical blue line on selected row. see below scheenshot.
![image](https://user-images.githubusercontent.com/11775081/182570008-a71de3fc-9dd5-4295-9ed4-046bd110712d.png)

2022-08-03 09:37 UTC, riccardo-forina commented
Good points Ajay! I think it would be ok to do that when moving this code to the ui-components repo to use the shared table there and keep this just as a bug fix for the reported issue. What do you think?

2022-08-04 14:33 UTC, ajaypratap003 approved these changes

2022-08-08 07:04 UTC, merged